//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuenosAires.BodegaBA.WsAnwoReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WsAnwoReference.IWsAnwo")]
    public interface IWsAnwo {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsAnwo/LeerTodoAnwoStockProducto", ReplyAction="http://tempuri.org/IWsAnwo/LeerTodoAnwoStockProductoResponse")]
        BuenosAires.Model.Respuesta LeerTodoAnwoStockProducto();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsAnwo/LeerTodoAnwoStockProducto", ReplyAction="http://tempuri.org/IWsAnwo/LeerTodoAnwoStockProductoResponse")]
        System.Threading.Tasks.Task<BuenosAires.Model.Respuesta> LeerTodoAnwoStockProductoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsAnwo/ReservarEquipoAnwo", ReplyAction="http://tempuri.org/IWsAnwo/ReservarEquipoAnwoResponse")]
        BuenosAires.Model.Respuesta ReservarEquipoAnwo(string nroserieanwo, string reservar_si_o_no);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsAnwo/ReservarEquipoAnwo", ReplyAction="http://tempuri.org/IWsAnwo/ReservarEquipoAnwoResponse")]
        System.Threading.Tasks.Task<BuenosAires.Model.Respuesta> ReservarEquipoAnwoAsync(string nroserieanwo, string reservar_si_o_no);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWsAnwoChannel : BuenosAires.BodegaBA.WsAnwoReference.IWsAnwo, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WsAnwoClient : System.ServiceModel.ClientBase<BuenosAires.BodegaBA.WsAnwoReference.IWsAnwo>, BuenosAires.BodegaBA.WsAnwoReference.IWsAnwo {
        
        public WsAnwoClient() {
        }
        
        public WsAnwoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WsAnwoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsAnwoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsAnwoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BuenosAires.Model.Respuesta LeerTodoAnwoStockProducto() {
            return base.Channel.LeerTodoAnwoStockProducto();
        }
        
        public System.Threading.Tasks.Task<BuenosAires.Model.Respuesta> LeerTodoAnwoStockProductoAsync() {
            return base.Channel.LeerTodoAnwoStockProductoAsync();
        }
        
        public BuenosAires.Model.Respuesta ReservarEquipoAnwo(string nroserieanwo, string reservar_si_o_no) {
            return base.Channel.ReservarEquipoAnwo(nroserieanwo, reservar_si_o_no);
        }
        
        public System.Threading.Tasks.Task<BuenosAires.Model.Respuesta> ReservarEquipoAnwoAsync(string nroserieanwo, string reservar_si_o_no) {
            return base.Channel.ReservarEquipoAnwoAsync(nroserieanwo, reservar_si_o_no);
        }
    }
}
