//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuenosAires.BodegaBA.WsGuiaDespachoReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WsGuiaDespachoReference.IWsGuiaDespacho")]
    public interface IWsGuiaDespacho {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsGuiaDespacho/ConsultarGuiaDespacho", ReplyAction="http://tempuri.org/IWsGuiaDespacho/ConsultarGuiaDespachoResponse")]
        BuenosAires.Model.Respuesta ConsultarGuiaDespacho();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsGuiaDespacho/ConsultarGuiaDespacho", ReplyAction="http://tempuri.org/IWsGuiaDespacho/ConsultarGuiaDespachoResponse")]
        System.Threading.Tasks.Task<BuenosAires.Model.Respuesta> ConsultarGuiaDespachoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsGuiaDespacho/ActualizarEstadoGuiaDespacho", ReplyAction="http://tempuri.org/IWsGuiaDespacho/ActualizarEstadoGuiaDespachoResponse")]
        BuenosAires.Model.Respuesta ActualizarEstadoGuiaDespacho(int nrogd, string estadogd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsGuiaDespacho/ActualizarEstadoGuiaDespacho", ReplyAction="http://tempuri.org/IWsGuiaDespacho/ActualizarEstadoGuiaDespachoResponse")]
        System.Threading.Tasks.Task<BuenosAires.Model.Respuesta> ActualizarEstadoGuiaDespachoAsync(int nrogd, string estadogd);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWsGuiaDespachoChannel : BuenosAires.BodegaBA.WsGuiaDespachoReference.IWsGuiaDespacho, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WsGuiaDespachoClient : System.ServiceModel.ClientBase<BuenosAires.BodegaBA.WsGuiaDespachoReference.IWsGuiaDespacho>, BuenosAires.BodegaBA.WsGuiaDespachoReference.IWsGuiaDespacho {
        
        public WsGuiaDespachoClient() {
        }
        
        public WsGuiaDespachoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WsGuiaDespachoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsGuiaDespachoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsGuiaDespachoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public BuenosAires.Model.Respuesta ConsultarGuiaDespacho() {
            return base.Channel.ConsultarGuiaDespacho();
        }
        
        public System.Threading.Tasks.Task<BuenosAires.Model.Respuesta> ConsultarGuiaDespachoAsync() {
            return base.Channel.ConsultarGuiaDespachoAsync();
        }
        
        public BuenosAires.Model.Respuesta ActualizarEstadoGuiaDespacho(int nrogd, string estadogd) {
            return base.Channel.ActualizarEstadoGuiaDespacho(nrogd, estadogd);
        }
        
        public System.Threading.Tasks.Task<BuenosAires.Model.Respuesta> ActualizarEstadoGuiaDespachoAsync(int nrogd, string estadogd) {
            return base.Channel.ActualizarEstadoGuiaDespachoAsync(nrogd, estadogd);
        }
    }
}
